import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PageWrap } from "@/layout"; // Adjust the import path as necessary

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageWrap>{children}</PageWrap>
      </body>
    </html>
  );
}