/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vjXlGclmlEJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function PrivacyPolicy() {
  return (
    <div className="bg-background text-foreground">
      <main className="container mx-auto max-w-4xl px-4 py-12 md:px-6 md:py-16">
        <div className="space-y-6">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Privacy Policy</h1>
          <p className="mt-3 text-lg text-muted-foreground">
            At Paw-fect Pals, we are committed to protecting the privacy and security of our customers&apos; personal
            information. This privacy policy explains how we collect, use, and safeguard your data.
          </p>
          <section>
            <h2 className="text-xl font-bold">Data Collection</h2>
            <p className="my-3 text-lg text-muted-foreground">We collect the following information from our customers:</p>
            <ul className="list-disc space-y-2 pl-6">
              <li>Contact information, such as your name, email address, and phone number.</li>
              <li>Details about your pets, including their names, breeds, and any medical or dietary needs.</li>
              <li>Payment information, such as credit card details, for processing transactions.</li>
              <li>Location data, to provide location-based services and recommendations.</li>
            </ul>
          </section>
          <section>
            <h2 className="text-xl font-bold">Data Usage</h2>
            <p className="my-3 text-lg text-muted-foreground">We use the collected information to:</p>
            <ul className="list-disc space-y-2 pl-6">
              <li>
                Provide and improve our pet care services, such as scheduling appointments and recommending products.
              </li>
              <li>Communicate with you about your account, orders, and any updates or changes to our services.</li>
              <li>Personalize your experience and make relevant recommendations.</li>
              <li>Comply with legal and regulatory requirements.</li>
            </ul>
          </section>
          <section>
            <h2 className="text-xl font-bold">Data Sharing</h2>
            <p className="my-3 text-lg text-muted-foreground">We may share your personal information with the following third parties:</p>
            <ul className="list-disc space-y-2 pl-6">
              <li>Service providers, such as payment processors and shipping carriers, to facilitate our services.</li>
              <li>Affiliates and partners, but only with your consent and in accordance with this privacy policy.</li>
              <li>
                Law enforcement or government agencies, if required by law or to protect our rights and the safety of
                others.
              </li>
            </ul>
          </section>
          <section>
            <h2 className="text-xl font-bold">Data Security</h2>
            <p className="my-3 text-lg text-muted-foreground">
              We take the security of your personal information seriously and have implemented various measures to
              protect it, including:
            </p>
            <ul className="list-disc space-y-2 pl-6">
              <li>Encryption of sensitive data, such as payment information, during transmission and storage.</li>
              <li>Secure servers and firewalls to prevent unauthorized access to our systems.</li>
              <li>Regular security audits and updates to our infrastructure.</li>
            </ul>
          </section>
          <section>
            <h2 className="text-xl font-bold">Your Rights</h2>
            <p className="my-3 text-lg text-muted-foreground">As a customer, you have the following rights:</p>
            <ul className="list-disc space-y-2 pl-6">
              <li>Access your personal information and request corrections or updates.</li>
              <li>Opt-out of marketing communications or request the deletion of your data.</li>
              <li>
                File a complaint with the relevant data protection authority if you have concerns about how we handle
                your information.
              </li>
            </ul>
          </section>
          <div className="space-y-4">
            <h2 className="text-2xl font-bold">Contact Us</h2>
            <p>
              If you have any questions or concerns about our privacy practices, please contact us at{" "}
              <a href="#" className="text-primary underline">
                tomasi@tomasi.co.za
              </a>
              .
            </p>
          </div>
        </div>
      </main>
    </div>
  )
}
