/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/IrPC0g9GTyM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Rubik } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function TermsOfService() {
  return (
    <div className="bg-background text-foreground">
      <main className="container mx-auto max-w-4xl px-4 py-12 md:px-6 md:py-16">
        <div className="space-y-6">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Terms of Service</h1>
          <p className="mt-3 text-lg text-muted-foreground">
            Welcome to Paw-fect Pals, your trusted pet care service. By using our platform, you agree to the following
            terms and conditions.
          </p>
          <div className="space-y-4">
            <h2 className="text-2xl font-bold">User Eligibility</h2>
            <p className="text-muted-foreground">
              Our services are available to individuals aged 18 and above who are legally able to enter into a contract.
              By using our platform, you confirm that you meet these eligibility requirements.
            </p>
          </div>
          <div className="space-y-4">
            <h2 className="text-2xl font-bold">Service Descriptions</h2>
            <p className="text-muted-foreground">
              Paw-fect Pals offers a range of pet care services, including dog walking, pet sitting, and grooming. Our
              experienced and animal-loving team is dedicated to providing the best possible care for your furry friends.
            </p>
          </div>
          <div className="space-y-4">
            <h2 className="text-2xl font-bold">Pricing and Payments</h2>
            <p className="text-muted-foreground">
              Our pricing is transparent and competitive. You can view our current rates on our website. Payments can be
              made securely through our platform using a variety of payment methods. All prices are subject to change
              without notice.
            </p>
          </div>
          <div className="space-y-4">
            <h2 className="text-2xl font-bold">User Responsibilities</h2>
            <p className="text-muted-foreground">
              As a user of Paw-fect Pals, you are responsible for providing accurate information about your pet, including
              any special needs or medical conditions. You must also ensure that your pet is up-to-date on all necessary
              vaccinations and flea/tick prevention.
            </p>
          </div>
          <div className="space-y-4">
            <h2 className="text-2xl font-bold">Intellectual Property</h2>
            <p className="text-muted-foreground">
              All content and materials on the Paw-fect Pals platform, including our website, mobile app, and any related
              intellectual property, are owned by Paw-fect Pals or our licensors. You may not reproduce, modify, or
              distribute any of this content without our prior written consent.
            </p>
          </div>
          <div className="space-y-4">
            <h2 className="text-2xl font-bold">Termination</h2>
            <p className="text-muted-foreground">
              Paw-fect Pals reserves the right to terminate your access to our services at any time, for any reason,
              including if we reasonably believe that you have violated these terms of service. You may also cancel your
              account at any time, but you will not be entitled to a refund for any unused services.
            </p>
          </div>
          <div className="space-y-4">
            <h2 className="text-2xl font-bold">Disclaimers</h2>
            <p className="text-muted-foreground">
              Paw-fect Pals makes no warranties or representations about the accuracy, reliability, or timeliness of our
              services. We are not responsible for any injuries, illnesses, or damages that may occur to your pet while in
              our care, unless caused by our gross negligence or willful misconduct.
            </p>
          </div>
          <div className="space-y-4">
            <h2 className="text-2xl font-bold">Contact Us</h2>
            <p>
              If you have any questions or concerns about our privacy practices, please contact us at{" "}
              <a href="#" className="text-primary underline">
                tomasi@tomasi.co.za
              </a>
              .
            </p>
          </div>
        </div>
      </main>
    </div>
  )
}
